export const ADD_TODO = 'ADD_TODO'; 
export const REMOVE_TODO = 'REMOVE_TODO'; 
export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE'; 
export const FILTER = 'FILTER'; 

export const LOAD_NEWS = "LOAD_NEWS";

export const HANDLE_SUBMIT_LOGIN ="HANDLE_SUBMIT_LOGIN"; 
export const HANDLE_SUBMIT_LOGOUT ="HANDLE_SUBMIT_LOGOUT"; 
export const LOAD_ARTICLE_PER_CLICK ="LOAD_ARTICLE_PER_CLICK"; 
export const LOAD_ALL_ARTICLES ="LOAD_ALL_ARTICLES"; 
export const DELETE_ALL_ARTICLES ="DELETE_ALL_ARTICLES"; 
export const OPEN_VIRTUAL_WALLET ="OPEN_VIRTUAL_WALLET"; 
export const ADD_SUM_VALUE ="ADD_SUM_VALUE"; 
 



 

